[2016-03-31 23:09:09,868: WARNING/MainProcess] /home/yubang/software/env/python/community_name_card/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2016-03-31 23:09:09,949: INFO/MainProcess] Connected to redis://127.0.0.1:6379/4
[2016-03-31 23:09:09,962: INFO/MainProcess] mingle: searching for neighbors
[2016-03-31 23:09:10,970: INFO/MainProcess] mingle: all alone
[2016-03-31 23:09:11,028: WARNING/MainProcess] worker@yubang-pc ready.
[2016-03-31 23:09:11,033: INFO/MainProcess] Received task: dao.card_dao.update_card_redundancy_labels[d9ed5fb1-4a35-453b-b86e-ca1db51d8761]
[2016-03-31 23:09:11,036: INFO/MainProcess] Received task: dao.card_dao.update_card_redundancy_labels[946038ec-fd99-4908-ac1a-d3a11759240d]
[2016-03-31 23:09:11,126: INFO/MainProcess] Task dao.card_dao.update_card_redundancy_labels[946038ec-fd99-4908-ac1a-d3a11759240d] succeeded in 0.0882494420002s: None
[2016-03-31 23:09:11,127: INFO/MainProcess] Task dao.card_dao.update_card_redundancy_labels[d9ed5fb1-4a35-453b-b86e-ca1db51d8761] succeeded in 0.0919474429975s: None
